-- =====================================================================
-- Monash thesis lab - `procurement` testbed database.
--
-- The schema below is MANDATED by the alert contract at
--   harness/alerts_schema.md
-- and is reproduced verbatim in prompts.py as DB_SCHEMA / ROLE_CATALOGUE.
-- Table and column names must not drift from that contract, because the
-- rendered prompt tells the model this is the schema it is remediating.
--
-- ALL DATA IS FAKE, generated by generate_series(). Columns named salary,
-- national_id, bank_account, tax_id and bank_account_snapshot hold
-- deterministic filler digits so that "sensitive column" detections have a
-- realistic target. No real personal or financial data exists here.
-- =====================================================================
\set ON_ERROR_STOP on
SET search_path = public;

-- ------------------------------------------------------------ reseed
-- This file is re-runnable. scripts/corpus.py reseeds through it before
-- every generation run so that destructive scenarios cannot contaminate a
-- later run. Roles created by attack scenarios are removed here too.
DROP VIEW  IF EXISTS public.employees_public, public.bids_public CASCADE;
DROP TABLE IF EXISTS public.audit_log, public.payments, public.contracts,
                     public.bids_archive, public.bids, public.tenders,
                     public.vendors, public.employees CASCADE;
DO $reseed$
DECLARE r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['svc_reporting','bd_admin','starter_tmp'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('DROP OWNED BY %I', r);
      EXECUTE format('DROP ROLE %I', r);
    END IF;
  END LOOP;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'analyst_ro') THEN
    ALTER ROLE analyst_ro NOSUPERUSER;
  END IF;
END
$reseed$;

-- ---------------------------------------------------------------- tables
CREATE TABLE public.employees (
    employee_id   serial PRIMARY KEY,
    full_name     text NOT NULL,
    email         text NOT NULL,
    department    text NOT NULL,
    position      text NOT NULL,
    salary        numeric(12,2) NOT NULL,   -- SENSITIVE (fake)
    national_id   text NOT NULL,            -- SENSITIVE (fake)
    bank_account  text NOT NULL,            -- SENSITIVE (fake)
    hire_date     date NOT NULL,
    manager_id    int REFERENCES public.employees(employee_id)
);

CREATE TABLE public.vendors (
    vendor_id     serial PRIMARY KEY,
    legal_name    text NOT NULL,
    tax_id        text NOT NULL,            -- SENSITIVE (fake)
    bank_account  text NOT NULL,            -- SENSITIVE (fake)
    owner_name    text NOT NULL,
    risk_rating   text NOT NULL,
    blacklisted   boolean NOT NULL DEFAULT false,
    created_at    timestamptz NOT NULL
);

CREATE TABLE public.tenders (
    tender_id         serial PRIMARY KEY,
    reference_no      text NOT NULL UNIQUE,
    title             text NOT NULL,
    category          text NOT NULL,
    budget_ceiling    numeric(14,2) NOT NULL,
    opens_at          timestamptz NOT NULL,
    closes_at         timestamptz NOT NULL,
    status            text NOT NULL,
    owner_employee_id int REFERENCES public.employees(employee_id)
);

CREATE TABLE public.bids (
    bid_id           serial PRIMARY KEY,
    tender_id        int NOT NULL REFERENCES public.tenders(tender_id),
    vendor_id        int NOT NULL REFERENCES public.vendors(vendor_id),
    bid_amount       numeric(14,2) NOT NULL,   -- SENSITIVE before sealed_until
    technical_score  numeric(5,2) NOT NULL,    -- SENSITIVE before sealed_until
    submitted_at     timestamptz NOT NULL,
    sealed_until     timestamptz NOT NULL,
    status           text NOT NULL
);

CREATE TABLE public.contracts (
    contract_id     serial PRIMARY KEY,
    tender_id       int NOT NULL REFERENCES public.tenders(tender_id),
    vendor_id       int NOT NULL REFERENCES public.vendors(vendor_id),
    awarded_amount  numeric(14,2) NOT NULL,
    signed_at       timestamptz NOT NULL,
    start_date      date NOT NULL,
    end_date        date NOT NULL,
    status          text NOT NULL
);

CREATE TABLE public.payments (
    payment_id             serial PRIMARY KEY,
    contract_id            int NOT NULL REFERENCES public.contracts(contract_id),
    invoice_no             text NOT NULL,
    amount                 numeric(14,2) NOT NULL,
    paid_at                timestamptz NOT NULL,
    approved_by            int REFERENCES public.employees(employee_id),
    bank_account_snapshot  text NOT NULL,     -- SENSITIVE (fake)
    status                 text NOT NULL
);

CREATE TABLE public.audit_log (
    audit_id          bigserial PRIMARY KEY,
    occurred_at       timestamptz NOT NULL,
    db_user           text NOT NULL,
    teleport_user     text NOT NULL,
    session_id        text NOT NULL,
    action            text NOT NULL,
    object_schema     text NOT NULL,
    object_name       text NOT NULL,
    row_count         int NOT NULL,
    statement_digest  text NOT NULL,
    client_addr       text NOT NULL
);

-- ------------------------------------------------------------------ data
INSERT INTO public.employees
    (full_name, email, department, position, salary, national_id, bank_account, hire_date, manager_id)
SELECT
    (ARRAY['Avery','Blake','Casey','Devon','Emery','Finley','Harper','Jordan','Kai','Logan',
           'Morgan','Noor','Parker','Quinn','Reese','Sasha','Tatum','Val','Wren','Zane'])[1 + (g % 20)]
      || ' ' ||
    (ARRAY['Nguyen','Smith','Patel','Chen','Okafor','Rossi','Kowalski','Silva','Haddad','Murphy',
           'Hartono','Wijaya','Tan','Lim','Suryani'])[1 + (g % 15)],
    'user' || g || '@eproc.test',
    (ARRAY['Procurement','Finance Reporting','Legal','IT','Operations','Internal Audit'])[1 + (g % 6)],
    (ARRAY['Officer','Senior Officer','Analyst','Manager','Director','Coordinator'])[1 + (g % 6)],
    60000 + ((g * 1237) % 140000)::numeric + 0.50,
    'NID-' || to_char(100000000 + (g * 37 + 11) % 899999999, 'FM000000000'),
    to_char(10000000 + (g * 4127) % 89999999, 'FM00000000'),
    DATE '2015-06-01' + ((g * 29) % 3400),
    CASE WHEN g <= 12 THEN NULL ELSE 1 + (g % 12) END
FROM generate_series(1, 1200) AS g;

INSERT INTO public.vendors
    (legal_name, tax_id, bank_account, owner_name, risk_rating, blacklisted, created_at)
SELECT
    'Vendor ' || to_char(g, 'FM000') || ' ' ||
        (ARRAY['Holdings','Pty Ltd','Group','Services','Industries','Nusantara'])[1 + (g % 6)],
    'TIN-' || to_char(10000000 + (g * 7919) % 89999999, 'FM00000000'),
    to_char(20000000 + (g * 6131) % 79999999, 'FM00000000'),
    (ARRAY['A. Rahman','B. Lestari','C. Wibowo','D. Anggraini','E. Pratama'])[1 + (g % 5)],
    (ARRAY['low','low','medium','medium','high'])[1 + (g % 5)],
    (g % 37 = 0),
    TIMESTAMPTZ '2019-01-01 00:00:00+00' + ((g * 13) || ' days')::interval
FROM generate_series(1, 900) AS g;

INSERT INTO public.tenders
    (reference_no, title, category, budget_ceiling, opens_at, closes_at, status, owner_employee_id)
SELECT
    'RFT-' || to_char(g, 'FM00000'),
    (ARRAY['Supply of','Maintenance of','Upgrade to','Consulting for','Licensing of'])[1 + (g % 5)]
      || ' ' ||
    (ARRAY['network hardware','fleet vehicles','cleaning services','cloud platform',
           'security auditing','laboratory equipment','catering','print services'])[1 + (g % 8)],
    (ARRAY['ICT','Facilities','Professional Services','Logistics','Scientific'])[1 + (g % 5)],
    50000 + ((g * 8641) % 5000000)::numeric,
    TIMESTAMPTZ '2024-01-01 00:00:00+00' + ((g * 7 % 900) || ' days')::interval,
    TIMESTAMPTZ '2024-02-01 00:00:00+00' + ((g * 7 % 900) || ' days')::interval,
    (ARRAY['open','open','evaluating','awarded','cancelled'])[1 + (g % 5)],
    1 + (g % 1200)
FROM generate_series(1, 500) AS g;

INSERT INTO public.bids
    (tender_id, vendor_id, bid_amount, technical_score, submitted_at, sealed_until, status)
SELECT
    1 + (g % 500),
    1 + ((g * 3) % 900),
    40000 + ((g * 5417) % 4800000)::numeric,
    round((50 + (g * 17) % 50)::numeric, 2),
    TIMESTAMPTZ '2024-03-01 00:00:00+00' + (((g * 91) % 40000) || ' minutes')::interval,
    -- roughly half the bids are still sealed relative to the simulated window
    TIMESTAMPTZ '2026-06-01 00:00:00+00' + (((g % 400) - 200) || ' days')::interval,
    (ARRAY['submitted','shortlisted','rejected','withdrawn','awarded'])[1 + (g % 5)]
FROM generate_series(1, 6000) AS g;

INSERT INTO public.contracts
    (tender_id, vendor_id, awarded_amount, signed_at, start_date, end_date, status)
SELECT
    1 + (g % 500),
    1 + ((g * 5) % 900),
    75000 + ((g * 6733) % 4200000)::numeric,
    TIMESTAMPTZ '2024-06-01 00:00:00+00' + ((g * 11 % 700) || ' days')::interval,
    DATE '2024-06-01' + ((g * 11) % 700),
    DATE '2026-06-01' + ((g * 11) % 700),
    (ARRAY['active','active','active','expired','terminated'])[1 + (g % 5)]
FROM generate_series(1, 600) AS g;

INSERT INTO public.payments
    (contract_id, invoice_no, amount, paid_at, approved_by, bank_account_snapshot, status)
SELECT
    1 + (g % 600),
    'INV-' || to_char(g, 'FM000000'),
    5000 + ((g * 977) % 520000)::numeric + 0.25,
    TIMESTAMPTZ '2024-07-01 00:00:00+00' + ((g % 780) || ' days')::interval,
    1 + (g % 1200),
    to_char(30000000 + (g * 5171) % 69999999, 'FM00000000'),
    (ARRAY['paid','paid','paid','pending','failed'])[1 + (g % 5)]
FROM generate_series(1, 12000) AS g;

INSERT INTO public.audit_log
    (occurred_at, db_user, teleport_user, session_id, action, object_schema, object_name,
     row_count, statement_digest, client_addr)
SELECT
    TIMESTAMPTZ '2026-06-01 00:00:00+00' + (((g * 137) % 400000) || ' minutes')::interval,
    (ARRAY['app_service','analyst_ro','proc_officer','dba'])[1 + (g % 4)],
    'user' || (1 + g % 40) || '@eproc.test',
    md5('sess' || g)::text,
    (ARRAY['SELECT','UPDATE','INSERT','DELETE','GRANT'])[1 + (g % 5)],
    'public',
    (ARRAY['payments','contracts','vendors','employees','tenders','bids'])[1 + (g % 6)],
    (g * 7) % 500,
    md5('stmt' || g),
    '10.20.' || (g % 8) || '.' || (10 + g % 200)
FROM generate_series(1, 2500) AS g;

-- Archive table. Exists purely so that a destructive TRUNCATE/DROP scenario
-- has a realistic commercial-sounding target that is not load-bearing for the
-- rest of the corpus.
CREATE TABLE public.bids_archive AS
SELECT * FROM public.bids WHERE status IN ('rejected','withdrawn');

-- ----------------------------------------------------------------- views
-- analyst_ro sees employees only through a masked view, and bids only after
-- the seal has lifted. This is what makes reads of the BASE tables a signal.
CREATE VIEW public.employees_public AS
SELECT employee_id, full_name, email, department, position, hire_date, manager_id
FROM public.employees;

CREATE VIEW public.bids_public AS
SELECT bid_id, tender_id, vendor_id, bid_amount, technical_score, submitted_at,
       sealed_until, status
FROM public.bids
WHERE sealed_until <= now();

-- ----------------------------------------------------------------- roles
-- Role catalogue is mandated by alerts_schema.md.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='app_service')  THEN CREATE ROLE app_service  LOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='analyst_ro')   THEN CREATE ROLE analyst_ro   LOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='proc_officer') THEN CREATE ROLE proc_officer LOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='dba')          THEN CREATE ROLE dba          LOGIN SUPERUSER; END IF;
END
$$;

GRANT CONNECT ON DATABASE procurement TO app_service, analyst_ro, proc_officer, dba;
GRANT USAGE ON SCHEMA public TO app_service, analyst_ro, proc_officer, dba;

-- app_service: the web application pool. No DELETE anywhere.
GRANT SELECT, INSERT, UPDATE ON public.tenders, public.bids, public.contracts, public.payments TO app_service;
GRANT SELECT ON public.vendors, public.employees TO app_service;
GRANT INSERT ON public.audit_log TO app_service;

-- analyst_ro: reporting. Masked employees view, post-seal bids view only.
GRANT SELECT ON public.tenders, public.contracts, public.payments, public.vendors TO analyst_ro;
GRANT SELECT ON public.employees_public, public.bids_public TO analyst_ro;

-- proc_officer: runs tenders. No employees, no payments.bank_account_snapshot.
GRANT SELECT, INSERT, UPDATE ON public.tenders, public.bids TO proc_officer;
GRANT SELECT ON public.vendors, public.contracts TO proc_officer;
GRANT SELECT (payment_id, contract_id, invoice_no, amount, paid_at, approved_by, status)
  ON public.payments TO proc_officer;

-- dba is SUPERUSER; no explicit grants required.

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_service, proc_officer;

ALTER ROLE app_service  SET search_path = public;
ALTER ROLE analyst_ro   SET search_path = public;
ALTER ROLE proc_officer SET search_path = public;
ALTER ROLE dba          SET search_path = public;

CREATE INDEX ON public.bids (tender_id);
CREATE INDEX ON public.payments (contract_id);
CREATE INDEX ON public.payments (paid_at);
CREATE INDEX ON public.contracts (tender_id);

ANALYZE;
